/**
 *    @file  config.hpp
 *   @brief  Configure header file.
 *
 *  This template is generated by the build script defining some macros about
 *  project revision.
 *
 *  @author  Ali Ghaffaari (\@cartoonist), <ali.ghaffaari@mpi-inf.mpg.de>
 *
 *  @internal
 *       Created:  Fri Feb 24, 2020  18:40
 *  Organization:  Max-Planck-Institut fuer Informatik
 *     Copyright:  Copyright (c) 2019, Ali Ghaffaari
 *
 *  This source code is released under the terms of the MIT License.
 *  See LICENSE file for more information.
 */

#ifndef  KSEQPP_CONFIG_HPP__
#define  KSEQPP_CONFIG_HPP__

#define KSEQPP_PROJECT_VERSION "@PROJECT_VERSION@"
#define KSEQPP_PROJECT_VERSION_MAJOR "@PROJECT_VERSION_MAJOR@"
#define KSEQPP_PROJECT_VERSION_MINOR "@PROJECT_VERSION_MINOR@"
#define KSEQPP_PROJECT_VERSION_PATCH "@PROJECT_VERSION_PATCH@"

#endif  /* --- #ifndef KSEQPP_CONFIG_HPP__ --- */